language: java
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
install: /bin/true
script: mvn checkstyle:check test package
before_deploy:
  - export RELEASE_JAR_FILE=$(ls target/saltstack-netapi-client-*.jar)
  - echo "Deploying $RELEASE_JAR_FILE to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: Gzz8W8cnLBgui3dh9yCl+z72qLd22T2N35QBqEIZIB38WGDMfKliQ2xrxYz4YkH3SeH+rcu8xzL9gEKd7YIA7pp6R7Q5wy+i2F2whC8kbC8qaOQLvpNfdzadwLS11ExtqSOMebxphJxzMYXjW/LWQ2AH4Df7wUwTy+cVX9oRWfs=
  file_glob: true
  file: "${RELEASE_JAR_FILE}"
  skip_cleanup: true
  on:
    repo: SUSE/saltstack-netapi-client-java
    tags: true
